"""Add is_active column to Employee

Revision ID: 1abc2c43690e
Revises: ab53941fc711
Create Date: 2025-08-24 21:03:12.209634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1abc2c43690e'
down_revision: Union[str, Sequence[str], None] = 'ab53941fc711'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_column('employees', 'is_active')
    # ### end Alembic commands ###
