"""add route_vendor_assign table with user link

Revision ID: 9c11e8fae11d
Revises: 5f002ee949db
Create Date: 2025-08-26 23:36:42.125819

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c11e8fae11d'
down_revision: Union[str, Sequence[str], None] = '5f002ee949db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shift_routes', sa.Column('vendor_id', sa.Integer(), nullable=True))
    op.add_column('shift_routes', sa.Column('vehicle_id', sa.Integer(), nullable=True))
    op.add_column('shift_routes', sa.Column('driver_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'shift_routes', 'vehicles', ['vehicle_id'], ['vehicle_id'])
    op.create_foreign_key(None, 'shift_routes', 'drivers', ['driver_id'], ['driver_id'])
    op.create_foreign_key(None, 'shift_routes', 'vendors', ['vendor_id'], ['vendor_id'])
  
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_constraint(None, 'shift_routes', type_='foreignkey')
    op.drop_constraint(None, 'shift_routes', type_='foreignkey')
    op.drop_constraint(None, 'shift_routes', type_='foreignkey')
    op.drop_column('shift_routes', 'driver_id')
    op.drop_column('shift_routes', 'vehicle_id')
    op.drop_column('shift_routes', 'vendor_id')
    # ### end Alembic commands ###
