"""new tables for route conforamtion

Revision ID: f8cf8aba508a
Revises: 9e8a96bfbf89
Create Date: 2025-08-26 12:39:32.332405

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8cf8aba508a'
down_revision: Union[str, Sequence[str], None] = '9e8a96bfbf89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shift_route_stops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shift_route_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.String(), nullable=False),
    sa.Column('employee_name', sa.String(), nullable=True),
    sa.Column('pickup_lat', sa.Float(), nullable=False),
    sa.Column('pickup_lng', sa.Float(), nullable=False),
    sa.Column('pickup_address', sa.Text(), nullable=True),
    sa.Column('landmark', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['shift_route_id'], ['shift_routes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('shift_routes', 'confirmed',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_index(op.f('ix_shift_routes_id'), table_name='shift_routes')
    op.create_index('ix_shift_routes_date_shift', 'shift_routes', ['route_date', 'shift_id'], unique=False)
    op.create_unique_constraint('uq_shift_route', 'shift_routes', ['shift_id', 'route_date', 'route_number'])
    op.drop_constraint(op.f('shift_routes_shift_id_fkey'), 'shift_routes', type_='foreignkey')
    op.create_foreign_key(None, 'shift_routes', 'shifts', ['shift_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shift_routes', type_='foreignkey')
    op.create_foreign_key(op.f('shift_routes_shift_id_fkey'), 'shift_routes', 'shifts', ['shift_id'], ['id'])
    op.drop_constraint('uq_shift_route', 'shift_routes', type_='unique')
    op.drop_index('ix_shift_routes_date_shift', table_name='shift_routes')
    op.create_index(op.f('ix_shift_routes_id'), 'shift_routes', ['id'], unique=False)
    op.alter_column('shift_routes', 'confirmed',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_table('shift_route_stops')
    # ### end Alembic commands ###
